import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "../components/sideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  modals,
  children,
}: {
  modals: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-cols-10 min-h-screen`}
      >
        <div className="col-span-2 min-w-[200px]">
          <SideBar></SideBar>
        </div>
        <div className="col-span-8">
          {children}
        </div>
        {modals}
      </body>
    </html>
  );
}
