import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "../components/sideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  modals,
  children,
}: {
  modals: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex`}
      >
        <div className="w-14 lg:w-52 fixed top-0 left-0 z-20 h-screen bg-gray-100">
          <SideBar></SideBar>
        </div>
        <div className="flex-1 ml-14 lg:ml-52 min-w-[820px]">
          {children}
        </div>
        {modals}
      </body>
    </html>
  );
}
